#!/bin/sh

mkdir -p tmp/undo
mkdir -p tmp/view

while getopts 'iu' OPT; do
	case $OPT in
		i)
			echo "Instalando plugins..."
			mkdir -p pack
			cd pack
			git submodule update --init
			git submodule add https://github.com/Raimondi/delimitMate plugins/start/delimitMate
			git submodule add https://github.com/ctrlpvim/ctrlp.vim plugins/start/ctrlp.vim
			git submodule add https://github.com/srcery-colors/srcery-vim colors/start/srcery-vim
			git submodule add https://github.com/tpope/vim-commentary plugins/start/vim-commentary
			git submodule add https://github.com/tpope/vim-fugitive plugins/start/vim-fugitive
			git submodule add https://github.com/tpope/vim-surround plugins/start/vim-surround
			;;
		u)
			echo "Actualizando plugins..."
			git submodule update --remote --merge
			;;
		?)
			echo "Usa '-i' para instalar los plugins, y '-u' para actualizarlos."
			;;
	esac
done

